### PR TITLE
Adding React Native Slides and PDF version

### PR DESCRIPTION
**Pull request by ben-edgar**
Slides: https://docs.google.com/presentation/d/1ESIruAjTa7FXpebfcU6DFzUZWJKltVrbyxAYrVk4wG8/edit#slide=id.p
Sanitized slides: https://docs.google.com/presentation/d/18rj_iudTDygLu_7kvgZSwIMknMWdbbHOhahJHWfB-bA/edit

### CODE REVIEW

**Comment by ben-edgar** [comment]
@n-kumari @lcc8we @megantracy93 please review!

**Comment by FuadBalashov** [comment]
Links look good
The path for the new files look good
content looks good except for slide 8:
1) Could you add speaker notes to provide more info on what you are depicting in the slide (eg, what you would say when showing the slide)
2) It may be clearer to just have `render()` instead of `React.renderComponent()` as the starting thing.
3) Should we include an arrow pointing away from Update to a new box that says `Unmounted`?


I was looking at this image online and I think its just a bit clearer but very similar: https://www.codevoila.com/uploads/images/201607/reactjs_component_lifecycle_status.png

**Comment by megantracy93** [comment]
@FuadBalashov I addressed your comments in the original slides.  @ben-edgar I also updated the table of contents and sanitized the speaker notes.  I wasn't sure the protocol for updating the Github copy, so can you port over those changes?

**Comment by ben-edgar** [comment]
@FuadBalashov @megantracy93 @lcc8we @n-kumari addressed all comments. Ready for final review!

**Comment by n-kumari** [comment]
React component lifecycle link was referring to the detailed lifecycle slide. Changed it to simplified react lifecycle slide. 

Added link to detailed react lifecycle

Some of our heading we fontsize 24 and some 28. I change all of them to 28 except slide 30 as it already had too many texts in it.

**Comment by ben-edgar** [comment]
@n-kumari did you change both the git slides and the non-git ones? I'm thinking maybe we just make the git slides our regular slides and try to not add any internal links! Updating 2 copies is a headache

**Comment by n-kumari** [comment]
I changed at both the places. 

But I agree that maintaining 2 copies feels 🙅

**Comment by ben-edgar** [comment]
Sweet I'll update this PR with the latest slides then

**Comment by ben-edgar** [comment]
@n-kumari I just updated the original name to be "Simple" react component lifecycle so I can keep the detailed one just "React Component Lifecycle" -- else it took up 2 lines. I'm going to merge this as is and we can update it  if we have any more updates.

**Comment by FuadBalashov** [comment]
Slides look good on drive. I have not reviewed the attached version.

**Pull request merged**
